# Generated by Django 5.2.12 on 2026-03-27 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        ('plan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'plan',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='sessions',
                        to='plan.plan',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'workout_session',
            },
        ),
        migrations.CreateModel(
            name='ExerciseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exercise_logs',
                        to='exercise.exercise',
                    ),
                ),
                (
                    'session',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='exercise_logs',
                        to='workout.workoutsession',
                    ),
                ),
            ],
            options={
                'db_table': 'exercise_log',
            },
        ),
        migrations.CreateModel(
            name='SetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                (
                    'exercise_log',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='workout.exerciselog'
                    ),
                ),
            ],
            options={
                'db_table': 'set_log',
                'indexes': [models.Index(fields=['exercise_log'], name='idx_set_log_exercise_log')],
            },
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['date'], name='idx_workout_session_date'),
        ),
        migrations.AddIndex(
            model_name='workoutsession',
            index=models.Index(fields=['user', 'date'], name='idx_workout_session_user_date'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['session'], name='idx_exercise_log_session'),
        ),
        migrations.AddIndex(
            model_name='exerciselog',
            index=models.Index(fields=['exercise'], name='idx_exercise_log_exercise'),
        ),
    ]
