# Generated by Django 5.2.12 on 2026-03-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutsession',
            name='notes',
        ),
    ]
