# Generated by Django 5.1.7 on 2026-03-23 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0001_initial'),
        ('workout', '0002_remove_notes_from_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='plan',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='sessions',
                to='plan.plan',
            ),
        ),
    ]
