# Generated by Django 5.2.12 on 2026-03-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
