# Generated by Django 5.2.12 on 2026-03-22 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'plan_weekly',
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sets', models.IntegerField(blank=True, null=True)),
                ('target_reps', models.IntegerField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plan_exercises',
                        to='exercise.exercise',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='plan.plan'
                    ),
                ),
            ],
            options={
                'db_table': 'plan_exercise',
                'indexes': [models.Index(fields=['plan'], name='idx_plan_exercise_plan')],
            },
        ),
        migrations.CreateModel(
            name='PlanWeeklyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='weekly_items', to='plan.plan'
                    ),
                ),
                (
                    'plan_weekly',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plan.planweekly'
                    ),
                ),
            ],
            options={
                'db_table': 'plan_weekly_item',
                'indexes': [
                    models.Index(fields=['plan_weekly'], name='idx_plan_weekly_item_weekly'),
                    models.Index(fields=['day_of_week'], name='idx_plan_weekly_item_day'),
                ],
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='chk_day_of_week'
                    )
                ],
            },
        ),
    ]
