# Generated by Django 5.2.12 on 2026-03-27 06:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('exercise', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=20)),
                ('is_template', models.BooleanField(default=False)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plans',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='PlanExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_index', models.IntegerField(default=0)),
                (
                    'exercise',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='plan_exercises',
                        to='exercise.exercise',
                    ),
                ),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='plan.plan'
                    ),
                ),
            ],
            options={
                'db_table': 'plan_exercise',
            },
        ),
        migrations.CreateModel(
            name='PlanWeekly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_template', models.BooleanField(default=False)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='weekly_plans',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'db_table': 'plan_weekly',
            },
        ),
        migrations.CreateModel(
            name='PlanWeeklyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField()),
                (
                    'plan',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='weekly_items', to='plan.plan'
                    ),
                ),
                (
                    'plan_weekly',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name='items', to='plan.planweekly'
                    ),
                ),
            ],
            options={
                'db_table': 'plan_weekly_item',
            },
        ),
        migrations.AddIndex(
            model_name='plan',
            index=models.Index(fields=['user'], name='idx_plan_user'),
        ),
        migrations.AddIndex(
            model_name='planexercise',
            index=models.Index(fields=['plan'], name='idx_plan_exercise_plan'),
        ),
        migrations.AddIndex(
            model_name='planweekly',
            index=models.Index(fields=['user'], name='idx_plan_weekly_user'),
        ),
        migrations.AddIndex(
            model_name='planweeklyitem',
            index=models.Index(fields=['plan_weekly'], name='idx_plan_weekly_item_weekly'),
        ),
        migrations.AddIndex(
            model_name='planweeklyitem',
            index=models.Index(fields=['day_of_week'], name='idx_plan_weekly_item_day'),
        ),
        migrations.AddConstraint(
            model_name='planweeklyitem',
            constraint=models.CheckConstraint(
                condition=models.Q(('day_of_week__gte', 1), ('day_of_week__lte', 7)), name='chk_day_of_week'
            ),
        ),
    ]
