# Generated by Django 5.2.12 on 2026-03-25 07:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planexercise',
            name='target_reps',
        ),
        migrations.RemoveField(
            model_name='planexercise',
            name='target_sets',
        ),
    ]
